# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best-practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/Enum/'
            - '../src/Domain/*/Exception/'
            - '../src/Domain/*/DTO/'
            - '../src/Kernel.php'

    App\Domain\User\Repository\UserRepositoryInterface: '@App\Infrastructure\Persistence\Doctrine\DoctrineUserRepository'

    App\Domain\CandidateProfile\Repository\CandidateProfileRepositoryInterface: '@App\Infrastructure\Persistence\Doctrine\DoctrineCandidateProfileRepository'

    App\Domain\Job\Repository\JobRepositoryInterface: '@App\Infrastructure\Persistence\Doctrine\DoctrineJobRepository'

    App\Infrastructure\ApiPlatform\OpenApi\JwtLoginDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@.inner']
